name: Lint and release with Goreleaser

on: 
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch

jobs: 
  golangci:
    name: Lint with Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  bump_version:
    needs: golangci
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        DEFAULT_BUMP: ${{github.event.inputs.bump}}

  goreleaser:
    needs: bump_version
    name: Release package with Goreleaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

