name: Lint and release with Goreleaser

on: 
  workflow_dispatch:

jobs: 
  golangci:
    name: Lint with Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  echo:
    name: Echo
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint
        run: echo Hello, Gopher!

