name: Lint and release with Goreleaser

on: 
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch

jobs: 
  golangci:
    name: Lint with Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  bump_version:
    needs: golangci
    name: Bump version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        TAG_PREFIX: v
        DEFAULT_BUMP: ${{github.event.inputs.bump}}

